FROM jenkins/jenkins:lts

USER root

# 1. Install static Docker CLI binary
ENV DOCKER_VERSION=24.0.7

RUN curl -fsSL -O https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz \
    && tar xzvf docker-${DOCKER_VERSION}.tgz \
    && mv docker/docker /usr/local/bin/ \
    && rm -rf docker docker-${DOCKER_VERSION}.tgz

# 2. Install standalone kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/

# 3. Add jenkins user to docker group
RUN groupadd -f -g 999 docker && usermod -aG docker jenkins

USER jenkins
